repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.256'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    - id: nbstripout
  # pre-commit built-in hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: requirements-txt-fixer
    exclude: "requirements-dit.txt"
  - id: check-merge-conflict
  - id: check-added-large-files
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
    exclude: ".*devcontainer.json"
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: "[/?\\w*/?]*(.xml|dummy_diff.json)"
  - id: trailing-whitespace
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: detect-private-key
-   repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
      - id: detect-missing-init
        args:
          [
            "--create",
            "--track",
            "--python-folders",
            "./preprocess/src/preprocess,./train/src/train",
          ]
